### ISSUE TITLE
Browser sync reload when add or remove images

### ISSUE THREAD

**Issue by illycz** [dsktschy/laravel-mix-copy-watched#17]
**Describe the bug**
Plugin work as expected, but Browser sync don't reload browser when copyWatched files are changed.

**Your environment**
 - macos
 - Node 14
 - laravel-mix 6.0.13
 - laravel-mix-copy-watched 2.3.0

**Your webpack.mix.js**
```
let mix = require('laravel-mix');

require('laravel-mix-copy-watched');

mix
  .setPublicPath('./assets/dist')
  .webpackConfig({
    externals: {
      'jquery': 'jQuery'
    }
  })
  .js('./assets/src/javascripts/app.js', 'javascripts')
  .sass('./assets/src/stylesheets/app.scss', 'stylesheets').options({
    processCssUrls: false
  })
  .copyWatched('./assets/src/images/**/*.{jpg,jpeg,png,gif,svg,webp,avif}', 'assets/dist/images')
  .browserSync({
    proxy: 'fajnarodina.local',
    watchEvents: ['add', 'change', 'unlink', 'addDir', 'unlinkDir'],
    files: [
      './assets/dist/**/*.css',
      './assets/dist/**/*.js',
      './assets/dist/**/*.{jpg,jpeg,png,gif,svg,webp,avif}',
      './**/*.php'
    ]
  });
```

**Comment by illycz** [comment]
When I'm watching all files together throu glob pattern `**/*`, also images refresh browser.
But when I specify only images or folder only with images, browser not respond.

Strange...

**Comment by dsktschy** [comment]
@illycz
Thank you for the report.

I have reproduced the same situation from your webpack.mix.js.
And, I compared the behavior of BrowserSync in the following two cases.

- Rewriting images in assets/dist/images by laravel-mix-copy-watched
- Rewriting images in assets/dist/images manually

Change, add, delete, all had the same behavior.
This means that laravel-mix-copy-watched does not change the behavior of BrowserSync in any way.
Therefore, if you have a problem with this behavior, please discuss it as a BrowserSync issue.

Also, check the following behavior.

> Changes you make will either be injected into the page (CSS & images) or will cause all browsers to do a full-page refresh.

https://browsersync.io/docs/options#option-files
When images are changed, BrowserSync does not reload, but injects.
If the target image is displayed in the page you are viewing in the browser, the changes to the image will be applied (injected), although no reload will occur.
If not displayed in the page, it will appear as if nothing is happening, because no reload or insertion will occur.

**Comment by illycz** [comment]
Thanks for your time,
it looks that image injection not working when image is added, changed or deleted.

I don't know if it's problem within browser-sync itself or browser-sync-webpack-plugin.
